# fly.toml app configuration file generated for pdex on 2024-01-10T16:18:15+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "pdex"
primary_region = "arn"

[build]

[env]
  PORT = "3000"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
