name: Health check

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test_schedule:
    runs-on: ubuntu-latest
    steps:
      - name: Every minute
        run: date
      - name: Check the root url
        uses: jtalk/url-health-check-action@v3
        with:
          url: https://kopy.fly.dev/
          max-attempts: 3
          retry-delay: 5s