name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: not skipped
        if: ${{ !contains(join(github.event.commits.*.message), '#skip') }}
        run: |
          echo "NO SKIP"
      - name: skipped
        if: ${{ contains(join(github.event.commits.*.message), '#skip') }}
        run: |
          echo "SKIP"