name: Deployment pipeline

on:
  push:
    branches:
      - main1
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  deploy_render:
    runs-on: ubuntu-20.04
    steps:
      - name: Trigger deployment
        run: curl ${{ secrets.RENDER_HOOK }} 