name: Testing stuff

on:
  push:
    branches:
      - main

jobs:
  a_test_job:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - name: has lol
        env:
          LOL: ${{ contains(join(github.event.commits.*.message), 'lol') }}
        run: echo "$LOL"
      - name: Say hello
        if: ${{ $LOL }}
        run: |
          echo "Hello World!"